### ISSUE TITLE
Run on node with electron

### ISSUE THREAD

**Issue by jl91** [supremainc/sfmdev#6]
hello guys, i'm write an application with electron to comunicate with a gym ratchet that use that libs, so as we know, electron uses nodejs to comunicate with hardware. Has some native lib to use with node that i can use UF_initSocket to comunicate with these hardware or can i use sockets to connect directly in ?

**Comment by hyeonchang** [comment]
I want to know what module you use, first. as you know you can communicate with hardware using the nodejs (such as 'serialport' or 'net'). 
Unfortunately, UF_initSocket was implemented based on the Windows API. also, the SFM SDK has the dependency on the platform. 
so UF_initSocket cannot be used directly with the nodejs. if you want to use the nodejs, you should implement all the functionality you need by yourself. 
we are considering to develop the new SDK supports the cross-platform in near future. 
the nodejs will be supported someday. but we are very sorry that it's not supported yet.

**Comment by jl91** [comment]
Hi, thx for answer. I'm developing an application for Gym's, i'm using a Gym Ratchet  "TCA slim IHM" from Tecnibra. It's a Brazilian vendor of Ratchets. This ratchet uses a software "SETEC" that do a proxy to the ratchet, I'm trying to use tcp socket, but it's really really unstable. sometimes when i send a message from my socket client to my socket server (this ratchet uses a socket server with the proxy software)  it's work, sometimes dont.

**Comment by jl91** [comment]
this is my sample socket server

var net = require('net');
var serverTCP = net.createServer((socket) => {
  socket.name = socket.remoteAddress + ':' + socket.remotePort;
  console.log('Socket Name: ' + socket.name);

// Mensagem de checagem de conexão  já testei com e sem essa mensagem 
// essa mensagem é disparada  apenas para os sockets que não sejam o da catraca.
  setInterval(() => {
    if (socket.remoteAddress !== '192.168.1.22') {
      socket.write('server_alive');
    }
  }, 5000);

  socket.on('data', (data) => {
// o socket recebe a mensagem em buffer depois convertemos para string, pensei 
// inclusive que ela pudesse perder o "\r" com a conversão e testei
// concatenando ou não o comando na hora de rodar o comando socket.write.

    const unbufferedData = data.toString();

// Já teste com e sem esse write, aparentemente quando eu subo o servidor de socket a 
// catraca se conecta automaticamente no server porém, não some a mensagem 
// a mensagem de "sem conexão", a menos que eu a bombadeie com essa mensagem. 
// ( parecido com o problema abaixo. )
//    socket.write('$');

// Se eu tirar esse IF a catraca entra em loop infinito e fica disparando a mensagem de recebido, 
// outro ponto em momento algum aqui eu tenho um retorno para
// avisar que o comando foi executado.
    if (unbufferedData === '$') {
      return;
    }
    console.log('commando recebido:');
    console.log(unbufferedData);
    socket.write(unbufferedData);

 // Comando original do servidor de teste, funciona se deixar somente ele executando, porém fica em looping conforme 
 // informado acima e esse loop deixa ela apitando e travada no comando.

//    socket.write("01;02;E;10;     Acesso     ;    Liberado    ;"+"\r");

  });

  socket.on('drain', (data) => {
    console.log(data);
  });

  socket.on('end', () => {
    console.log('connection ended');
  });

  socket.on('error', (error) => {
    console.log(error);
  });

});

// esse realmente é o ip da máquina o software da setec está configurado como dhcp (já tentei sem tbm).
serverTCP.listen(2050, '192.168.1.190');

**Comment by jl91** [comment]
and this is my socket client

var net = require('net');

const socket = net.createConnection({host: '192.168.1.190', port: 2050}, () => {
	console.log('conectado');
	socket.on('ready', () => {
		//console.log('aqui');
		socket.write("01;02;E;10;     Acesso     ;    Liberado    ;"+"\r");
		/*for(let i = 0; i < 100; i++){
			
		}*/
	});

	socket.on('data', (data) => {
		console.log("Data received from socket Server: "+data.toString());
	});
});

**Comment by jl91** [comment]
i've found the problem, thats working now, thx man.
